CREATE TABLE IF NOT EXISTS TBL_LOGIN_USER
(
UUID VARCHAR(100) PRIMARY KEY,
USERNAME VARCHAR(256) UNIQUE NOT NULL,
PASSWORD VARCHAR(256) NOT NULL,
STATUS VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS TBL_LOGIN_ROLE(
  UUID VARCHAR(100) PRIMARY KEY,
  ROLE_NAME VARCHAR(40) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS TBL_LOGIN_USER_ROLE_MAPPING(
   UUID VARCHAR(100) PRIMARY KEY,
   USER_UUID VARCHAR(100) NOT NULL,
   ROLE_UUID VARCHAR(100) NOT NULL,
   FOREIGN KEY (USER_UUID) REFERENCES TBL_LOGIN_USER(UUID),
   FOREIGN KEY (ROLE_UUID) REFERENCES TBL_LOGIN_ROLE(UUID)
);