CREATE TABLE IF NOT EXISTS TBL_LOGIN_USER
(
UUID VARCHAR(100) PRIMARY KEY,
USERNAME VARCHAR(256) UNIQUE NOT NULL,
PASSWORD VARCHAR(256) NOT NULL,
STATUS VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS TBL_LOGIN_ROLE(
  UUID VARCHAR(100) PRIMARY KEY,
  ROLE_NAME VARCHAR(40) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS TBL_LOGIN_USER_ROLE_MAPPING(
   UUID VARCHAR(100) PRIMARY KEY,
   USER_UUID VARCHAR(100) NOT NULL,
   ROLE_UUID VARCHAR(100) NOT NULL,
   FOREIGN KEY (USER_UUID) REFERENCES TBL_LOGIN_USER(UUID),
   FOREIGN KEY (ROLE_UUID) REFERENCES TBL_LOGIN_ROLE(UUID)
);
CREATE TABLE IF NOT EXISTS DRAFT_TOKEN(
USERNAME VARCHAR(100) UNIQUE NOT NULL,
DRAFT_TOKEN VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS TBL_USER_PROFILE(
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) PRIMARY KEY,
    MOBILE VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    USER_UUID VARCHAR(100) UNIQUE NOT NULL,
    FOREIGN KEY (USER_UUID) REFERENCES TBL_LOGIN_USER(UUID)
);

CREATE TABLE IF NOT EXISTS TBL_USER_OTP(
    USER_NAME VARCHAR(256)  NOT NULL,
    OTP INT NOT NULL,
    CREATED_AT BIGINT(20) NOT NULL
);